<a href="https://colab.research.google.com/github/kujiwa/testIncolab/blob/main/samHawp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

samHawp

In [1]:
!git clone https://github.com/kujiwa/testIncolab.git

Cloning into 'testIncolab'...
remote: Enumerating objects: 108, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 108 (delta 3), reused 0 (delta 0), pack-reused 100
Receiving objects: 100% (108/108), 55.34 KiB | 4.61 MiB/s, done.
Resolving deltas: 100% (37/37), done.


In [2]:
!apt install ninja-build

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  ninja-build
0 upgraded, 1 newly installed, 0 to remove and 18 not upgraded.
Need to get 111 kB of archives.
After this operation, 358 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 ninja-build amd64 1.10.1-1 [111 kB]
Fetched 111 kB in 0s (1,329 kB/s)
Selecting previously unselected package ninja-build.
(Reading database ... 120876 files and directories currently installed.)
Preparing to unpack .../ninja-build_1.10.1-1_amd64.deb ...
Unpacking ninja-build (1.10.1-1) ...
Setting up ninja-build (1.10.1-1) ...
Processing triggers for man-db (2.10.2-1) ...


In [ ]:
import sys
sys.path.append('./testIncolab/amp_extensions/afm')
import torch
import numpy as np
from torch.utils.data.dataloader import default_collate
from csrc import _C

height=16
width =16
import torch

device='cuda'
lines = torch.Tensor([[0, 0, 1, 1], [1, 4, 2, 3], [4, 4, 8, 7],[9,7,8,3]]).to(device)
print(lines)
print(_C)
lmap, labels, _ = _C.encodels(lines,height,width,height,width,lines.size(0))
#print(lmap)
#print(labels)
print(lmap.size())#(6,height,width)
print(labels.size())#(lines_num,height,width)
print(labels)
#查看特定像素点(13,13)的label
# y_index=13
# z_index=13
print(labels[:,4,4])#(f,f,t,f)
print(labels[:,1,1])#(t,f,f,f)
print(labels[:,4,5])#(f,f,t,f)
print(labels[:,8,8])#(f,f,f,f)
print(labels[:,10,9])#(f,f,f,f)
print(labels[:,15,5])#(f,f,f,f)


dismap = torch.sqrt(lmap[0]**2+lmap[1]**2)[None]
print(dismap.size())
print(dismap)
print(dismap[0,4,4])
print(dismap[0,1,1])
print(dismap[0,4,5])
print(dismap[0,8,8])
print(dismap[0,10,9])
print(dismap[0,15,5])
#距离像素点1之外的都是false？


tensor([[0., 0., 1., 1.],
        [1., 4., 2., 3.],
        [4., 4., 8., 7.],
        [9., 7., 8., 3.]], device='cuda:0')
<module '_C' from '/root/.cache/torch_extensions/py310_cu118/_C/_C.so'>
torch.Size([6, 16, 16])
torch.Size([4, 16, 16])
tensor([[[ True,  True,  True,  ..., False, False, False],
         [ True,  True, False,  ..., False, False, False],
         [ True, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        [[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        [[False, F

In [ ]:
import torch

if torch.cuda.is_available():
    print("CUDA is available!")
else:
    print("CUDA is not available.")

print(torch.version.cuda)

CUDA is available!
11.8


In [ ]:
#把linesegment.cu里的1都改成3 看看t和f
#最后三个点的t和f不同，且距离计算也不同
#1好像是为了判断投影点在不在线上 而不是点到线段距离之类的

#如果有一个点投影在线上，但是距线很远，会不会是true
#测试方法 找到距离中所有>1的，看看是不是全部为ffff
#把linesegment.cu里的1都改成3 看看t和f
#最后三个点的t和f不同，且距离计算也不同
#1好像是为了判断投影点在不在线上
import sys
sys.path.append('./testIncolab/amp_extensions/afm')
import torch
import numpy as np
from torch.utils.data.dataloader import default_collate
from csrc import _C

height=16
width =16
import torch

device='cuda'
lines = torch.Tensor([[0, 0, 1, 1], [1, 4, 2, 3], [4, 4, 8, 7],[9,7,8,3]]).to(device)
print(lines)
print(_C)
lmap, labels, _ = _C.encodels(lines,height,width,height,width,lines.size(0))
#print(lmap)
#print(labels)
print(lmap.size())#(6,height,width)
print(labels.size())#(lines_num,height,width)
print(labels)
#查看特定像素点(13,13)的label
# y_index=13
# z_index=13
print(labels[:,4,4])#(f,f,t,f)
print(labels[:,1,1])#(t,f,f,f)
print(labels[:,4,5])#(f,f,t,f)
print(labels[:,8,8])#(f,f,f,f)
print(labels[:,10,9])#(f,f,f,f)
print(labels[:,15,5])#(f,f,f,f)


dismap = torch.sqrt(lmap[0]**2+lmap[1]**2)[None]
print(dismap.size())
print(dismap)
print(dismap[0,4,4])
print(dismap[0,1,1])
print(dismap[0,4,5])
print(dismap[0,8,8])
print(dismap[0,10,9])
print(dismap[0,15,5])
#距离像素点1之外的都是false
for i in range(dismap.size(1)):
    for j in range(dismap.size(2)):
        if dismap[0, i, j] > 1:
            print("dis:",dismap[0, i, j])
            print("i",i,"j",j)
            print(labels[:,i,j])
            # do something
#dismap 是距离 label是标签 如果全为f 说明无法投影到任何一条线段上（写得tql😭


tensor([[0., 0., 1., 1.],
        [1., 4., 2., 3.],
        [4., 4., 8., 7.],
        [9., 7., 8., 3.]], device='cuda:0')
<module '_C' from '/root/.cache/torch_extensions/py310_cu118/_C/_C.so'>
torch.Size([6, 16, 16])
torch.Size([4, 16, 16])
tensor([[[ True,  True,  True,  ..., False, False, False],
         [ True,  True, False,  ..., False, False, False],
         [ True, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        [[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        [[False, F

dismap 是距离 label是标签 如果全为f 说明无法投影到任何一条线段上

In [ ]:
#.so报错的时候先跑一下
!python /content/testIncolab/amp_extensions/afm/yjh_sizeTest.py

tensor([[0., 0., 1., 1.],
        [1., 4., 2., 3.],
        [4., 4., 8., 7.]], device='cuda:0')
<module '_C' from '/root/.cache/torch_extensions/py310_cu118/_C/_C.so'>
tensor([[[ 0.0000e+00, -5.0000e-01, -1.0000e+00,  ..., -5.1600e+00,
          -6.0000e+00, -7.0000e+00],
         [ 5.0000e-01, -4.7684e-07, -1.0000e+00,  ..., -5.0000e+00,
          -6.0000e+00, -7.0000e+00],
         [ 1.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -5.0000e+00,
          -6.0000e+00, -7.0000e+00],
         ...,
         [ 1.0000e+00,  0.0000e+00,  5.0400e+00,  ..., -5.0000e+00,
          -6.0000e+00, -7.0000e+00],
         [ 1.0000e+00,  5.8800e+00,  5.5200e+00,  ..., -5.0000e+00,
          -6.0000e+00, -7.0000e+00],
         [ 1.0000e+00,  6.3600e+00,  6.0000e+00,  ..., -5.0000e+00,
          -6.0000e+00, -7.0000e+00]],

        [[ 0.0000e+00,  5.0000e-01,  1.0000e+00,  ...,  6.8800e+00,
           7.0000e+00,  7.0000e+00],
         [-5.0000e-01, -4.7684e-07,  0.0000e+00,  ...,  6.0000e+00,
           6.

In [3]:
#测试改进程序 linesegment-hawp中tmap的值为分配线段标号（从0开始）
import sys
sys.path.append('./testIncolab/amp_extensions/afm')
import torch
import numpy as np
from torch.utils.data.dataloader import default_collate
from csrc import _C

height=16
width =16
import torch

device='cuda'
lines = torch.Tensor([[0, 0, 1, 1], [1, 4, 2, 3], [4, 4, 8, 7],[9,7,8,3]]).to(device)
print(lines)
print(_C)
lmap, labels, tmap = _C.encodels(lines,height,width,height,width,lines.size(0))
#print(lmap)
#print(labels)
print(lmap.size())#(6,height,width)
print(labels.size())#(lines_num,height,width)
print(tmap.size())#(lines_num,height,width)
print(labels)
#查看特定像素点(13,13)的label
# y_index=13
# z_index=13
print(labels[:,4,4])#(f,f,t,f)
print(tmap[0,4,4])#(f,f,t,f)
print(labels[:,1,1])#(t,f,f,f)
print(labels[:,4,5])#(f,f,t,f)
print(tmap[0,4,5])
print(labels[:,8,8])#(f,f,f,f)
print(labels[:,10,9])#(f,f,f,f)
print(tmap[0,10,9])#(f,f,f,f)
print(labels[:,15,5])#(f,f,f,f)


dismap = torch.sqrt(lmap[0]**2+lmap[1]**2)[None]
print(dismap.size())
print(dismap)
print(dismap[0,4,4])
print(dismap[0,1,1])
print(dismap[0,4,5])
print(dismap[0,8,8])
print(dismap[0,10,9])
print(dismap[0,15,5])
#距离像素点1之外的都是false
for i in range(dismap.size(1)):
    for j in range(dismap.size(2)):
        if dismap[0, i, j] > 1:
            print("dis:",dismap[0, i, j])
            print("i",i,"j",j)
            print(labels[:,i,j])
            # do something
#dismap 是距离 label是标签 如果全为f 说明无法投影到任何一条线段上（写得tql😭


tensor([[0., 0., 1., 1.],
        [1., 4., 2., 3.],
        [4., 4., 8., 7.],
        [9., 7., 8., 3.]], device='cuda:0')
<module '_C' from '/root/.cache/torch_extensions/py310_cu118/_C/_C.so'>
torch.Size([6, 16, 16])
torch.Size([4, 16, 16])
torch.Size([1, 16, 16])
tensor([[[ True,  True,  True,  ..., False, False, False],
         [ True,  True, False,  ..., False, False, False],
         [ True, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False]],

        [[False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         ...,
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, False],
         [False, False, False,  ..., False, False, Fals

hawp环境配置
1.记得下载ckpt文件hawpv3-imagenet-03a84.pth

In [ ]:
!git clone https://github.com/cherubicXN/hawp.git

Cloning into 'hawp'...
remote: Enumerating objects: 982, done.
remote: Counting objects: 100% (705/705), done.
remote: Compressing objects: 100% (465/465), done.
remote: Total 982 (delta 293), reused 591 (delta 227), pack-reused 277
Receiving objects: 100% (982/982), 6.80 MiB | 18.28 MiB/s, done.
Resolving deltas: 100% (393/393), done.


In [ ]:
!apt install ninja-build

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  ninja-build
0 upgraded, 1 newly installed, 0 to remove and 18 not upgraded.
Need to get 111 kB of archives.
After this operation, 358 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 ninja-build amd64 1.10.1-1 [111 kB]
Fetched 111 kB in 0s (1,336 kB/s)
Selecting previously unselected package ninja-build.
(Reading database ... 120875 files and directories currently installed.)
Preparing to unpack .../ninja-build_1.10.1-1_amd64.deb ...
Unpacking ninja-build (1.10.1-1) ...
Setting up ninja-build (1.10.1-1) ...
Processing triggers for man-db (2.10.2-1) ...


In [ ]:
!cd hawp;pip install -e .;pip install -r requirement.;python -c "import torch; print(torch.cuda.is_available())"

Obtaining file:///content/hawp
  Preparing metadata (setup.py) ... done
  Running setup.py develop for hawp
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.4/14.4 MB 66.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 705.7/705.7 kB 53.1 MB/s eta 0:00:00
True


In [ ]:
!python -m hawp.ssl.predict --ckpt hawpv3-imagenet-03a84.pth --threshold 0.05 --img 33044.jpg --device='cuda'

  0% 0/1 [00:00<?, ?it/s]Figure(1400x2097.82)
100% 1/1 [00:06<00:00,  6.81s/it]


sam环境配置
https://github.com/facebookresearch/segment-anything#model-checkpoints

In [ ]:
!pip install git+https://github.com/facebookresearch/segment-anything.git

In [ ]:
!pip install opencv-python pycocotools matplotlib onnxruntime onnx

sam&&hawp

备忘录
1.偶尔报错 xx.so no such file 先用python .py运行，再运行ipynb里的代码，不知道原理，但是问题能解决